services:
  backend:
    build: ./backend
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myappdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  frontend:
    build:
      context: ./frontend
    container_name: mon-projet-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # ← ce volume évite d'écraser node_modules dans le conteneur
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true




volumes:
  db_data:
